- cloudformation.yaml
will trigger an alert if the state machine fails (which means we're unable to update the ticker value)
> Execution alarm

- cloudformation.yaml
- src/query-lambda/queries.ts
- src/query-lambda/query-lambda.ts
1. Filter by currency
2. Allow only one country code (as this is all we're likely to need)
3. Also, use the `formatDateTime` helper that I forgot to use previously.
e.g. `SELECT SUM(amount) FROM acquisition_events_code WHERE country_code = 'US' AND currency = 'USD' AND timestamp > CAST('2018-12-19' AS TIMESTAMP)`
> Currency filter

- src/query-lambda/queries.ts
This wasn't a problem previously because we were comparing against a timestamp
> Fix date comparison

- cloudformation.yaml
The 'calculate' lambda polls the status of the athena query until the result is ready, or it has tried 5 times.
Sometimes it exceeds the limit, so I'm increasing the interval between polls.
Weirdly, the athena history page reports the query as taking ~3 seconds, but the query result is sometimes not available after 3 mins
> Increase retry interval

- cloudformation.yaml
the state machine sometimes times out polling the result of the athena query. This is weird and I think it's a problem in AWS but don't have time to investigate now and it's not urgent.
For now, only trigger the alarm if 2 runs fail in a row.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html
Period is 900 (seconds) because the state machine runs every 15 mins.
EvaluationPeriods is 2 because I want to alarm only if it fails on 2 consecutive runs.
Threshold is 2 because I want to alarm if both runs have failed.
> Increase failure alarm threshold to 2 in a row

- src/value-ticker/query-lambda/queries.ts
The formatting of the frequencyName field has changed since we migrated away from thrift.
This is what we now have in athena:
> Fix frequency names in query

- src/value-ticker/calculate-lambda/calculate-lambda.ts
- src/value-ticker/cloudformation.yaml
We need to run 2 tickers concurrently.
For simplicity (we have a tight deadline) we're just going to spin up a new stack and output to a different file in S3.
With this PR, the filename is set from a cloudformation parameter.
> Make filename configurable

- src/value-ticker/cloudformation.yaml
We need to create a second stack for the AU moment.
Currently the resource names clash with the existing stack - this is fixed by putting the CountryCode in the names
> Enable dual stacks

- src/lib/s3.ts
- src/value-ticker/calculate-lambda/calculate-lambda.ts
- src/value-ticker/calculate-lambda/local.ts
- src/value-ticker/cloudformation.yaml
- src/value-ticker/package.json
- src/value-ticker/query-lambda/local.ts
- src/value-ticker/query-lambda/query-lambda.ts
- src/value-ticker/riff-raff.yaml
- src/value-ticker/ticker.conf.json
This PR enables the same state machine to run for different ticker campaigns.
1. The state machine now takes a `Name` as an input, to tell it which campaign name to run for (currently US_2022 or AU_2022)
2. There are now two cloudwatch events, one for each campaign name
3. Any cloudformation parameters relating to the ticker config (e.g. startDate, currency) have been removed, and are now loaded from a ticker.conf.json file in S3. This file contains config for each campaign, and there's an example in this PR. The lambdas have to load this config.
This means we now have to maintain ticker settings in an S3 file at: `membership-private/${Stage}/ticker.conf.json`.
And the only part of the repo that is aware of the ticker campaign names is the cloudwatch events in the cloudformation.yaml.
> Config to support two campaigns

- src/value-ticker/query-lambda/queries.ts
Trello card: https://trello.com/c/WSEGOVkC/1240-%F0%9F%87%A6%F0%9F%87%BA-australia-banner-alter-tickers-backend
This PR changes the value ticker to use a query that counts the number of supporters (rather than the numeric value of support).
@tomrf1 and I have tested in code that the state machine now reads the correct data when called with the AUS ticker name. We can’t test the ticker in code because SDC always queries the prod S3 files for ticker data. Once this is merged we should be able to see the prod ticker data in code by creating a ticker-containing banner in the code RRCP.
> Use supporter count query for ticker (for australian banner)

- src/value-ticker/query-lambda/queries.ts
This PR removes the currency filter from the `supporterCountQuery`. A currency filter is required for the other queries as they return monetary values, and we shouldn’t be mixing currencies on queries used to display monetary values, however it is not needed for a “supporter count” ticker. The stakeholder pointed this out and made the request.
[Trello](https://trello.com/c/YdwCMkXN/1313-server-side-updates-for-aus-10-year-anniversary-moments-ticker)
> Remove currency from the supporterCountQuery

- src/value-ticker/riff-raff.yaml
The lambda build step should have a dependency on the cloudformation step, so that they don’t conflict. This is described [in the Riff Raff documentation](https://riffraff.gutools.co.uk/docs/reference/riff-raff.yaml.md).
> Riff Raff: Add cloudformation dependency to lambda build

- .github/workflows/ci.yaml
Github Actions: Stop using guardian/actions-setup-node and use actions/setup-node instead
[**Trello Card**](https://trello.com/c/dlZA1kOt/1546-github-actions-stop-using-guardian-actions-setup-node-and-use-actions-setup-node-instead)
The [actions-setup-node repo ] (https://github.com/guardian/actions-setup-node) says that  has been archived by the owner on Dec 5, 2022 and will not be updated.
The official Github [actions/setup-node](https://github.com/marketplace/actions/setup-node-js-environment) now has [some support for node version files](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file).
You should use that instead.
> Update to actions/setup-node@v3

- docs/campaign-setup.md
- src/value-ticker/README.md
- src/value-ticker/cloudformation.yaml
- src/value-ticker/query-lambda/local.ts
- src/value-ticker/ticker.conf.json
Since we’re re-using the ticker from last year, it seems sensible to remove the year from the name. Adding a new ticker each year doesn’t seem like the right way to go about things. This PR will need to be co-ordinated with the similar ones on support-dotcom-components and support-admin-console.
> Remove _2022 from ticker names

- src/value-ticker/query-lambda/queries.ts
US Ticker backend changes to reflect an amounts target(value of the support) instead of the supporter count ( the number of supporters ). The new total is: $1.5m
Trello card [Here](https://trello.com/c/M8O4Tc2Q/1599-us-ticker-backend-changes)
Tested the change  in CODE .
Instead of showing the supporter count , the US.json in the https://s3.console.aws.amazon.com/s3/object/contributions-ticker?region=eu-west-1&prefix=$STAGE/US.json file  would show the amounts targets (Replace the STAGE value  in the above) 
This change would be updated for AUS as well ,but the final target has not been confirmed yet for Australia.
Also we need to modify the  ticker.conf.json in membership-private for PROD  to below
Reference PR: https://github.com/guardian/contributions-ticker-calculator/pull/52
> US Ticker backend changes

- README.md
- package.json
- src/lambda.ts
- src/lib/bigquery.ts
- src/lib/models.ts
- src/lib/s3.ts
- yarn.lock
Completes the new implementation of the ticker-calculator.
It now sends a single query to BigQuery.
The query should be largely equivalent to [the queries in the old code](https://github.com/guardian/contributions-ticker-calculator/pull/68/files#diff-df6303f33c653117603f06e8ffccfaeb8d369cf4b0db78c625d5e7c832e773f5L1) which used athena.
The main difference is that we now include SupporterPlus and ThreeTier. These must come from the `fact_holding_acquisition` table, which is only updated daily. This is because the `amount` isn't available in the live `fact_aquisition_event` table.
So, contributions will be counted throughout the day, but SupporterPlus/ThreeTier are only added in daily.
> Use bigquery

- src/lib/bigquery.ts
It's useful to include the campaign end date in the query when looking at past campaigns. I'm currently comparing the the BigQuery + Athena results for last year's US moment.
This technically would not make a difference during a campaign.
> Set end dates in query

- src/lambda.ts
This is to match previous behaviour - see https://github.com/guardian/contributions-ticker-calculator/pull/62
> Round amount

- src/lib/bigquery.ts
If there's no data yet (because the campaign hasn't started) then bigquery returns `null`.
This PR uses [COALESCE](https://cloud.google.com/bigquery/docs/reference/standard-sql/conditional_expressions#coalesce) to return 0 in this case
> Prevent null values when no data

- cdk/lib/__snapshots__/ticker-calculator.test.ts.snap
- cdk/lib/ticker-calculator.ts
this can take more than the default 30 seconds
> Increase lambda timeout

- cdk/lib/__snapshots__/ticker-calculator.test.ts.snap
- cdk/lib/ticker-calculator.ts
- src/lib/bigquery.ts
Add a new schedule for AU to support the AUS  Nov Campaign on all major assets, their target will be $400,000 AUS dollars with a $20,000 headstart 
The AU ticker query should also include the  IAP acquisitions
> AUS ticker for Nov 2024 Campaign

- README.md
- cdk/lib/__snapshots__/ticker-calculator.test.ts.snap
- cdk/lib/ticker-calculator.ts
- src/lambda.ts
- src/lib/bigquery.ts
- src/lib/models.ts
- src/ticker.conf.json
This PR adds support for a new type of ticker that counts the number of supporters, rather than the amount of money.
This is for an upcoming campaign that will count acquisitions from all users globally, excluding AU.
The config in parameter store will need to include a new item for a `global` campaign:
```
"global": {
"type": "SupporterCount",
"StartDate": "2025-04-30",
"EndDate": "2025-05-23",
"ExcludedCountryCodes": ["AU"],
"InitialAmount": 0,
"GoalAmount": 50000
}
```
We'll also need to update support-admin-console + support-dotcom-components to support the new `global` ticker campaign. Currently they only allow `US` or `AU`.
Tested in CODE by running the lambda and checking for the new output file:
```
$ curl https://support.code.dev-theguardian.com/ticker/global.json …
```
> Global supporter count ticker

- src/lib/bigquery.ts
- src/lib/models.ts
- src/ticker.conf.json
this feature is no longer required, and setting `"ExcludedCountryCodes": []` causes it to build an invalid sql query
Test run in CODE:
> Remove exclusions from global count
